https://apim-petwil.azure-api.net/ch2/sessions
Ocp-Apim-Subscription-Key: 11872d97fcca483f9a2d9b1e0f037acd

###

https://ca-customerapi.proudhill-9c79432d.northeurope.azurecontainerapps.io/api/customers

###
### 
https://apim-petwil.azure-api.net/ch5/api/customers
Ocp-Apim-Subscription-Key: 11872d97fcca483f9a2d9b1e0f037acd

###
https://apim-petwil.azure-api.net/ch5/api/customers/getcustomerbyemail/user4@domain.com
Ocp-Apim-Subscription-Key: 11872d97fcca483f9a2d9b1e0f037acd

###
### 
https://apim-petwil.azure-api.net/ch5/api/customers
Ocp-Apim-Subscription-Key: 11872d97fcca483f9a2d9b1e0f037acd
Ocp-Apim-Trace: true

###
### 
POST https://apim-petwilprod.azure-api.net/ch5/api/customers
Ocp-Apim-Subscription-Key: 546dc785a0ac4c3d93f7992c7dcf76fa
Content-Type: application/json

{"personalNumber": "1919191919", "email":"someone@email.com","phoneNumber":"+35470274729", "address": {"country": "Iceland", "zipCode": "12345"}}