https://apim-petwil.azure-api.net/ch2/sessions
Ocp-Apim-Subscription-Key: 11872d97fcca483f9a2d9b1e0f037acd

###

https://ca-customerapi.proudhill-9c79432d.northeurope.azurecontainerapps.io/api/customers

###
### 
https://apim-petwil.azure-api.net/ch5/api/customers
Ocp-Apim-Subscription-Key: 11872d97fcca483f9a2d9b1e0f037acd

