name: Dev deploy
on:
  push:
    branches-ignore:
    - 'main'
    paths:
    - 'api/CustomerAPI/**' 
    - '.github/workflows/*'
jobs:
   deploy_to_dev:
    name: 'Dev deployment'
    uses: ./.github/workflows/main.yaml         #Call the existing workflow 
    secrets: inherit
    with:
      name: petwil
      environment: ''   