# on: [workflow_dispatch]

name: Customer Api
on:
  workflow_call:
   inputs:
       environment:
        type: string
        default: ''                                #Leave this empty by default, this will ensure that the base repo secrets are used for deployment to DEV (i.e. no Environment)
        description: 'Name of the environment'
       name:
        type: string
        default: petwil                    
        description: 'Suffix to use'
jobs:
  build-and-deploy:
   runs-on: ubuntu-latest
   environment: 
    name: ${{inputs.environment}}
    url: https://apim-${{inputs.name}}.azure-api.net/ch5/api/customers
   env:
        directory: api/CustomerAPI
        name: ${{ inputs.name }}    # Your POSTFIX
   steps:
    - uses: actions/checkout@main       # Checkout the code to the GitHub runner 
    - name: Log into Azure              # Log into Azure using the service credentials provided earlier
      uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Use dotnet tools to build and generate swagger
      run: |
        dotnet tool restore --tool-manifest .config/dotnet-tools.json
        dotnet restore 
        dotnet build
        dotnet swagger tofile --output $GITHUB_WORKSPACE/api/CustomerAPI/swagger-output/swagger.json $GITHUB_WORKSPACE/api/CustomerAPI/bin/Debug/net6.0/CustomerAPI.dll v1
      working-directory: ${{ env.directory }}
    - name: Upload swagger to Azure storage account
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload -f $GITHUB_WORKSPACE/api/CustomerAPI/swagger-output/swagger.json -n swagger.json -c apidefinitions --overwrite --connection-string ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
    - name: Build image with Azure Container Registry
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az acr build --registry acr${{ env.name }}.azurecr.io --image customerapi:${{ github.run_number }} . -f api/CustomerAPI/Dockerfile
    - name: Deploy API to Azure Container Apps 
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: rg-${{ env.name }}
        template: ${{ env.directory }}/Bicep/main.bicep
        parameters: dockerimagetag=${{ github.run_number }} name=${{ env.name }} apidefinitionurl=https://stg${{ env.name }}hack.blob.core.windows.net/apidefinitions/swagger.json?${{ secrets.AZURE_BLOB_SAS_TOKEN }}
        failOnStdErr: false